module.exports = { 
    RES_STATUS_SUCCESS: 1,
	RES_STATUS_FAIL: 0,
	RES_MSG_SAVE_SUCCESS: "Data is saved successfuly",
	RES_MSG_SAVE_FAIL: "Data saving is fail",
	RES_MSG_UPDATE_SUCCESS: "Data is updated successfuly",
	RES_MSG_UPDATE_FAIL: "Data updating is fail",
	RES_MSG_DELETE_SUCCESS: "Data is deleted successfuly",
	RES_MSG_DELETE_FAIL: "Data deletion is fail",
	RES_MSG_DATA_NOT_FOUND: "Data is not found",
	RES_MSG_DATA_FOUND: "Data is found",
	RES_MSG_SUCESS: "Success",
	RES_MSG_FAIL: "Failure",
    DONATION_STATUS_PENDING: 0,
    DONATION_STATUS_APPROVED: 1,
    DONATION_STATUS_REJECTED: 2,
}